AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  TableName:
    Type: String
    Default: 'Candidates'
    Description: dynamo table contains all the candidates
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'

Resources:
  candidates:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.candidates
      Runtime: nodejs14.x
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName    
      Events:
        CreateAPI:
          Type: Api
          Properties:
            Path: /candidates
            Method: POST
        OtherOperationsAPI:
          Type: Api
          Properties:
            Path: /candidates/{itemId}
            Method: ANY
        Getall:
              Type: Api
              Properties:
                Path: /candidates/getAll
                Method: GET

  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

